from .models import Action

ACTIONS = [
    Action("system.update", "Mise à jour système", "Système", "Met à jour les paquets système.", True, "", "apt update && upgrade"),
    Action("system.reboot", "Redémarrer le serveur", "Système", "Redémarre immédiatement le serveur.", True),
    Action("system.shutdown", "Éteindre le serveur", "Système", "Éteint immédiatement le serveur.", True),
    Action("pkg.install", "Installer un paquet", "Paquets", "Installe un paquet système.", True, "Nom du paquet", "htop"),
    Action("pkg.remove", "Supprimer un paquet", "Paquets", "Supprime un paquet système.", True, "Nom du paquet", "nginx"),
    Action("pkg.hold", "Exclure un paquet", "Paquets", "Empêche les mises à jour d'un paquet (apt).", True, "Nom du paquet", "docker-ce"),
    Action("pkg.unhold", "Réinclure un paquet", "Paquets", "Réautorise les mises à jour d'un paquet (apt).", True, "Nom du paquet", "docker-ce"),
    Action("service.restart", "Redémarrer un service", "Services", "Redémarre un service systemd.", True, "Nom du service", "nginx"),
    Action("service.start", "Démarrer un service", "Services", "Démarre un service systemd.", True, "Nom du service", "ssh"),
    Action("service.stop", "Arrêter un service", "Services", "Arrête un service systemd.", True, "Nom du service", "nginx"),
    Action("service.enable", "Activer au démarrage", "Services", "Active un service au boot.", True, "Nom du service", "ssh"),
    Action("service.disable", "Désactiver au démarrage", "Services", "Désactive un service au boot.", True, "Nom du service", "apache2"),
    Action("service.list", "Lister les services", "Services", "Affiche les services systemd actifs."),
    Action("service.status", "Statut d'un service", "Services", "Affiche le statut détaillé d'un service.", False, "Nom du service", "nginx"),
    Action("service.logs", "Logs d'un service", "Services", "Affiche les derniers journaux d'un service.", False, "Nom du service", "nginx"),
    Action("monitor.overview", "Vue globale des ressources", "Surveillance", "Vue synthétique CPU/RAM/disk/load/net."),
    Action("monitor.disk", "Espace disque", "Surveillance", "Affiche les volumes et l'espace utilisé."),
    Action("monitor.net", "Connexions réseau", "Surveillance", "Affiche les connexions réseau et ports en écoute."),
    Action("monitor.ip", "IP / hostname", "Surveillance", "Affiche l'hôte et les IP locales."),
    Action("monitor.ram", "Usage RAM", "Surveillance", "Affiche l'usage mémoire détaillé."),
    Action("monitor.cpu", "Usage CPU", "Surveillance", "Affiche l'usage CPU global et par cœur."),
    Action("monitor.temp", "Température CPU", "Surveillance", "Affiche les sondes disponibles."),
    Action("disk.mount", "Monter un disque", "Disques", "Monte un périphérique sur un point de montage.", True, "<device> <mountpoint>", "/dev/sdb1 /mnt/data"),
    Action("disk.list", "Lister les disques", "Disques", "Affiche les disques et points de montage."),
    Action("network.ifaces", "Interfaces réseau", "Réseau", "Affiche les interfaces et leurs adresses."),
    Action("network.ping", "Tester la connectivité", "Réseau", "Teste une cible réseau avec ping.", False, "Cible optionnelle", "1.1.1.1"),
    Action("fw.status", "Statut UFW", "Pare-feu", "Affiche les règles UFW actuelles."),
    Action("fw.enable", "Activer UFW", "Pare-feu", "Active le pare-feu UFW.", True),
    Action("fw.disable", "Désactiver UFW", "Pare-feu", "Désactive le pare-feu UFW.", True),
    Action("fw.allow", "Ajouter règle UFW", "Pare-feu", "Ajoute une règle UFW allow.", True, "Règle", "22/tcp"),
    Action("fw.delete", "Supprimer règle UFW", "Pare-feu", "Supprime une règle UFW par numéro.", True, "Numéro", "3"),
    Action("logs.system", "Logs système", "Logs", "Affiche les derniers logs système."),
    Action("tool.cockpit", "Installer Cockpit", "Outils", "Installe l'interface web Cockpit.", True),
    Action("tool.doctor", "Diagnostic système", "Outils", "Vérifie l'environnement local."),
    Action("app.update", "Mettre à jour Systek", "Systek", "Met à jour l'application installée dans /opt/systek.", True),
    Action("app.uninstall", "Désinstaller Systek", "Systek", "Indique la commande de désinstallation propre.", True),
    Action("app.version", "Afficher la version", "Systek", "Affiche la version courante."),
]
